# Author: Akira Kudo
# Created: 2024/04/02
# Last Updated: 2024/05/24

import numpy as np
import pandas as pd

def read_BSOID_labeled_csv(csv_path : str,
                           include_scorer : bool=False):
    """
    Reads a BSOID-labeled csv file to extract labels as well
    as the corresponding DLC data.

    :param str csv_path: Path to the BSOID labeled csv.
    :param bool include_scorer: Whether to include 'scorer' row as header.
    :returns np.ndarray label: Label extracted from the csv.
    :returns pd.DataFrame dlc_data: DLC data extracted from the csv.
    """
    header_rows = [0,1,2] if include_scorer else [1,2]
    df = pd.read_csv(csv_path, header=header_rows, index_col=2)
    label = df.iloc[:, 1].to_numpy().astype(np.int64)
    dlc_data = df.iloc[:, 2:]
    multiidx = pd.MultiIndex.from_tuples(dlc_data.columns, names=['bodyparts', 'coord'])
    dlc_data.columns = multiidx
    return label, dlc_data

def read_BSOID_labeled_features(csv_path : str):
    
    # ,label,SNOUT_RIGHTFOREPAW_dist,SNOUT_LEFTFOREPAW_dist,SNOUT_RIGHTHINDPAW_dist,SNOUT_LEFTHINDPAW_dist,SNOUT_TAILBASE_dist,RIGHTFOREPAW_LEFTFOREPAW_dist,RIGHTFOREPAW_RIGHTHINDPAW_dist,RIGHTFOREPAW_LEFTHINDPAW_dist,RIGHTFOREPAW_TAILBASE_dist,LEFTFOREPAW_RIGHTHINDPAW_dist,LEFTFOREPAW_LEFTHINDPAW_dist,LEFTFOREPAW_TAILBASE_dist,RIGHTHINDPAW_LEFTHINDPAW_dist,RIGHTHINDPAW_TAILBASE_dist,LEFTHINDPAW_TAILBASE_dist,SNOUT_RIGHTFOREPAW_angle,SNOUT_LEFTFOREPAW_angle,SNOUT_RIGHTHINDPAW_angle,SNOUT_LEFTHINDPAW_angle,SNOUT_TAILBASE_angle,RIGHTFOREPAW_LEFTFOREPAW_angle,RIGHTFOREPAW_RIGHTHINDPAW_angle,RIGHTFOREPAW_LEFTHINDPAW_angle,RIGHTFOREPAW_TAILBASE_angle,LEFTFOREPAW_RIGHTHINDPAW_angle,LEFTFOREPAW_LEFTHINDPAW_angle,LEFTFOREPAW_TAILBASE_angle,RIGHTHINDPAW_LEFTHINDPAW_angle,RIGHTHINDPAW_TAILBASE_angle,LEFTHINDPAW_TAILBASE_angle,SNOUT_disp,RIGHTFOREPAW_disp,LEFTFOREPAW_disp,RIGHTHINDPAW_disp,LEFTHINDPAW_disp,TAILBASE_disp
    # 0,28.0,88.98500124613443,114.02758820851645,256.38890711466473,179.969482421875,251.2792091369629,52.38503774007162,178.78149032592773,121.18601608276367,186.39457575480145,142.3785769144694,74.55849520365398,142.0857226053874,90.61095873514812,52.60395081837972,71.46708520253499,11.323366728140977,3.2824571812565857,1.4627300110618215,0.06463247249099419,-0.02407788379292583,30.392027877981874,-1.0143247383413083,-1.7537817436589287,-0.4878465742731903,0.2463423991570337,-7.12065356152012,-2.5766946735472334,0.6292221793717307,13.122784546986793,-1.27457591107086,26.738152980804443,7.24207143485546,28.436503410339355,4.9613809784253435,3.0606232831875486,14.000575621922811
    """
    Reads a BSOID-labeled feature file (generated by my code) 
    to extract labels as well as the corresponding feature data.

    :param str csv_path: Path to the BSOID labeled feature csv.
    
    :returns np.ndarray label: Label extracted from the csv.
    :returns pd.DataFrame features: Feature data extracted from the csv.
    """
    header_rows = [0]
    df = pd.read_csv(csv_path, header=header_rows, index_col=0)
    label = df.iloc[:, 0].to_numpy().astype(np.int64)
    features = df.iloc[:, 1:]
    return label, features

if __name__ == "__main__":
    import os
    # read_BSOID_labeled_csv
    if False:
        FILE_OF_INTEREST = r"312152_m2DLC_resnet50_WhiteMice_OpenfieldJan19shuffle1_1030000.csv"
        LABELED_PREFIX = r"Mar-10-2023labels_pose_40Hz"

        MOUSETYPE_FOLDER = r"Z:\Raymond Lab\2 Colour D1 D2 Photometry Project\Akira\Leland B-SOID YAC128 Analysis" + \
                        r"\YAC128\YAC128" # r"\Q175\WT"

        LABELED_CSV_PATH = os.path.join(MOUSETYPE_FOLDER,  
                                        "CSV files", "BSOID", #r"csv/BSOID/Feb-27-2024"
                                        LABELED_PREFIX + FILE_OF_INTEREST)

        label, dlc_data = read_BSOID_labeled_csv(LABELED_CSV_PATH)
        print(f"label: {label}")
        print(f"label.shape: {label.shape}")
        print(f"dlc_data: {dlc_data}")
        print(f"dlc_data.columns: {dlc_data.columns}")


    if True:
        LABELED_FEATURE_CSV = r"Z:\Raymond Lab\2 Colour D1 D2 Photometry Project\Akira\BSOID\YAC128\labeled_features\allcsv_2024_05_16_Akira\HD_filt\Feb-23-2023_308535_m1DLC_resnet50_WhiteMice_OpenfieldJan19shuffle1_1030000_filtered_labeled_features.csv"
        
        label, features = read_BSOID_labeled_features(csv_path=LABELED_FEATURE_CSV)
        print(f"label: {label}")
        print(f"label.shape: {label.shape}")
        print(f"features: {features}")
        print(f"features.columns: {features.columns}")